# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(650, 500)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tableWidgetGames = QtGui.QTableWidget(self.centralWidget)
        self.tableWidgetGames.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidgetGames.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidgetGames.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetGames.setObjectName(_fromUtf8("tableWidgetGames"))
        self.tableWidgetGames.setColumnCount(4)
        self.tableWidgetGames.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetGames.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetGames.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetGames.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetGames.setHorizontalHeaderItem(3, item)
        self.tableWidgetGames.horizontalHeader().setMinimumSectionSize(1)
        self.tableWidgetGames.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidgetGames.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidgetGames)
        self.frame = QtGui.QFrame(self.centralWidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widgetLeft = QtGui.QWidget(self.frame)
        self.widgetLeft.setObjectName(_fromUtf8("widgetLeft"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widgetLeft)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.labelTotalGamesToIdle = QtGui.QLabel(self.widgetLeft)
        self.labelTotalGamesToIdle.setObjectName(_fromUtf8("labelTotalGamesToIdle"))
        self.verticalLayout_2.addWidget(self.labelTotalGamesToIdle)
        self.labelTotalGamesInRefund = QtGui.QLabel(self.widgetLeft)
        self.labelTotalGamesInRefund.setIndent(10)
        self.labelTotalGamesInRefund.setObjectName(_fromUtf8("labelTotalGamesInRefund"))
        self.verticalLayout_2.addWidget(self.labelTotalGamesInRefund)
        self.labelTotalRemainingDrops = QtGui.QLabel(self.widgetLeft)
        self.labelTotalRemainingDrops.setObjectName(_fromUtf8("labelTotalRemainingDrops"))
        self.verticalLayout_2.addWidget(self.labelTotalRemainingDrops)
        self.labelSteamNotRunning = QtGui.QLabel(self.widgetLeft)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelSteamNotRunning.setFont(font)
        self.labelSteamNotRunning.setStyleSheet(_fromUtf8("color: red"))
        self.labelSteamNotRunning.setObjectName(_fromUtf8("labelSteamNotRunning"))
        self.verticalLayout_2.addWidget(self.labelSteamNotRunning)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.widgetLeft)
        spacerItem1 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.labelHeaderImage = QtGui.QLabel(self.frame)
        self.labelHeaderImage.setMinimumSize(QtCore.QSize(292, 136))
        self.labelHeaderImage.setBaseSize(QtCore.QSize(292, 136))
        self.labelHeaderImage.setText(_fromUtf8(""))
        self.labelHeaderImage.setObjectName(_fromUtf8("labelHeaderImage"))
        self.horizontalLayout.addWidget(self.labelHeaderImage)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 650, 20))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionQuit = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("application-exit"))
        self.actionQuit.setIcon(icon)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionSettings = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("preferences-other"))
        self.actionSettings.setIcon(icon)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionRefresh = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("view-refresh"))
        self.actionRefresh.setIcon(icon)
        self.actionRefresh.setObjectName(_fromUtf8("actionRefresh"))
        self.actionStartStopIdle = QtGui.QAction(MainWindow)
        self.actionStartStopIdle.setEnabled(False)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("media-playback-start"))
        self.actionStartStopIdle.setIcon(icon)
        self.actionStartStopIdle.setObjectName(_fromUtf8("actionStartStopIdle"))
        self.actionNext = QtGui.QAction(MainWindow)
        self.actionNext.setEnabled(False)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("media-skip-forward"))
        self.actionNext.setIcon(icon)
        self.actionNext.setObjectName(_fromUtf8("actionNext"))
        self.actionShowAll = QtGui.QAction(MainWindow)
        self.actionShowAll.setCheckable(True)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("folder-open"))
        self.actionShowAll.setIcon(icon)
        self.actionShowAll.setObjectName(_fromUtf8("actionShowAll"))
        self.actionStartStopMultiIdle = QtGui.QAction(MainWindow)
        self.actionStartStopMultiIdle.setEnabled(False)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("media-playback-start"))
        self.actionStartStopMultiIdle.setIcon(icon)
        self.actionStartStopMultiIdle.setObjectName(_fromUtf8("actionStartStopMultiIdle"))
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionRefresh)
        self.toolBar.addAction(self.actionShowAll)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStartStopIdle)
        self.toolBar.addAction(self.actionNext)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStartStopMultiIdle)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Steam Idle", None))
        self.tableWidgetGames.setSortingEnabled(True)
        item = self.tableWidgetGames.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Game", None))
        item = self.tableWidgetGames.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Remaining drops", None))
        item = self.tableWidgetGames.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Playtime", None))
        self.labelTotalGamesToIdle.setText(_translate("MainWindow", "games left to idle", None))
        self.labelTotalGamesInRefund.setText(_translate("MainWindow", "in refund period (<2h play time)", None))
        self.labelTotalRemainingDrops.setText(_translate("MainWindow", "remaining card drops", None))
        self.labelSteamNotRunning.setText(_translate("MainWindow", "Steam client is not running.<br/>Please (re)start Steam.", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "Toolbar", None))
        self.actionQuit.setText(_translate("MainWindow", "&Quit", None))
        self.actionSettings.setText(_translate("MainWindow", "&Settings", None))
        self.actionRefresh.setText(_translate("MainWindow", "Refresh", None))
        self.actionRefresh.setToolTip(_translate("MainWindow", "Refresh/update the list of games, cards and playtime", None))
        self.actionRefresh.setShortcut(_translate("MainWindow", "F5", None))
        self.actionStartStopIdle.setText(_translate("MainWindow", "&Start Idle", None))
        self.actionStartStopIdle.setToolTip(_translate("MainWindow", "Start ideling", None))
        self.actionNext.setText(_translate("MainWindow", "&Next", None))
        self.actionNext.setToolTip(_translate("MainWindow", "Idle next game", None))
        self.actionShowAll.setText(_translate("MainWindow", "Show all", None))
        self.actionShowAll.setToolTip(_translate("MainWindow", "Show all apps (with and without remaining drops)", None))
        self.actionStartStopMultiIdle.setText(_translate("MainWindow", "Start &Multi-Idle", None))
        self.actionStartStopMultiIdle.setToolTip(_translate("MainWindow", "Start parallel idle of all games in refund period", None))

